added bookRepo and bookService classes
DmytroHadiuchko/Spring-BOOT pull request #1
Opened 2024-04-15 13:51 UTC by DmytroHadiuchko

2024-04-15 15:15 UTC, andrii-hoienko requested changes
I don`t see that all requirements are met, please check task description again

2024-04-15 15:15 UTC, andrii-hoienko commented on src/main/java/dmytro/hadiuchko/springboot/entity/Book.java
> +public class Book {
Please add table annotation

2024-04-15 15:15 UTC, andrii-hoienko commented on src/main/resources/application.properties
> +
```suggestion
```

2024-04-15 15:15 UTC, andrii-hoienko commented on src/main/resources/application.properties
> +spring.datasource.password=password
Don`t push credentials to remote, it is not safe

2024-04-15 15:15 UTC, andrii-hoienko commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/BookServiceImpl.java
> +    }
```suggestion
@Service
@RequiredArgsConstructor
public class BookServiceImpl implements BookService {
    private final BookRepository bookRepository;

```

2024-04-15 15:15 UTC, andrii-hoienko commented on src/main/java/dmytro/hadiuchko/springboot/Application.java
>  import org.springframework.boot.autoconfigure.SpringBootApplication;
Requirement: 'Class with @SpringBootApplication annotation that will have a CommandLineRunner bean'. I don`t see these changes

2024-04-15 15:15 UTC, andrii-hoienko commented on pom.xml
>          </dependency>
Did you add checkstyle plugin?

2024-04-15 15:43 UTC, DmytroHadiuchko commented on pom.xml
>          </dependency>
Yes, it was in first commit, in main branch

https://github.com/DmytroHadiuchko/Spring-BOOT/blob/d760259120ec7fb4f02c096f7da87f49e7d8d470/pom.xml#L42

2024-04-16 07:54 UTC, karma-o approved these changes
Looks okay, but the main problem is that we can not see around half of the changes in that PR, because they are already in the main branch, which is not good. Every change should be merged to main via a PR, especially some business logic like repository/service etc.

2024-04-16 08:14 UTC, merged