Add category
DmytroHadiuchko/Spring-BOOT pull request #10
Opened 2024-05-14 08:36 UTC by DmytroHadiuchko

2024-05-14 17:26 UTC, makaroshyna requested changes
I think you have comits from your previos PR here too.

2024-05-14 17:26 UTC, makaroshyna commented on src/main/java/dmytro/hadiuchko/springboot/controller/CategoryController.java
> +    @PreAuthorize("hasRole('USER')")
I think every user-accessible point should also have full admin access.

2024-05-14 17:26 UTC, makaroshyna commented on src/main/java/dmytro/hadiuchko/springboot/dto/category/request/CategoryRequestDto.java
> +        String name,
You can add max size too.

2024-05-14 17:26 UTC, makaroshyna commented on src/main/java/dmytro/hadiuchko/springboot/dto/category/request/CategoryRequestDto.java
> +public record CategoryRequestDto(
Maybe CreateCategoryRequestDto will be a better name? Idk

2024-05-14 17:26 UTC, makaroshyna commented on src/main/resources/db/changelog/changes/13-insert-values-to-book_category.yaml
Don't add actual IDs, it will be better to do SELECT queries to find what you need.

2024-05-15 11:37 UTC, d1sam requested changes
There are a lot of changes, that not related to this hw. please create a correct pr

2024-05-15 12:39 UTC, closed without merging