added shopping cart
DmytroHadiuchko/Spring-BOOT pull request #14
Opened 2024-05-17 16:04 UTC by DmytroHadiuchko

2024-05-20 09:03 UTC, karma-o requested changes
So far so good, but we need to make several improvements

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/controller/ShoppingCartController.java
> +                                      @PathVariable Long cartItemsId) {
```suggestion
                                      @PathVariable Long cartItemId) {
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/dto/cartitem/AddCartItemDto.java
> +    private int quantity;
* what will happen if user sends null here?
* do we want to have an item with 0 quantity? I think it would be better to remove that item completely rather then allowing to set it to 0

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/dto/cartitem/UpdateCartItemRequestDto.java
> +    private int quantity;
same here

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/entity/CartItem.java
> +@Setter
Let's not forget about equals, hashcode and toString, just exclude lazy-initialized files from them

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/entity/ShoppingCart.java
> +@Setter
same

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +                .collect(Collectors.toCollection(LinkedHashSet::new));
could be just `stream.toSet()` or `stream.collect(Collectors.toSet())`

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto getById(Long id) {
```suggestion
    public ShoppingCartDto getById(Long userId) {
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +        return cartItemMapper.toDto(cartItem);
you do not have to call save 2 times, just set a shopping cart id to a cart item, and save that cart item

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCart;
```suggestion
        return repo.save(shoppingCart);
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/UserServiceImpl.java
> +        shoppingCartRepository.save(shoppingCartService.createShoppingCart(savedUser));
```suggestion
        shoppingCartService.createShoppingCart(savedUser);
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/UserServiceImpl.java
> +        return userMapper.toUserResponse(repository.save(savedUser));
saving a savedUser does not look very good :)
```suggestion
        return userMapper.toUserResponse(savedUser);
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +    private ShoppingCart getShoppingCart(Long userid) {
```suggestion
    private ShoppingCart getShoppingCartForUser(Long userId) {
```

2024-05-20 09:03 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCart createShoppingCart(User user) {
```suggestion
    public ShoppingCart createShoppingCartForUser(User user) {
```

2024-05-20 09:38 UTC, karma-o commented on src/main/java/dmytro/hadiuchko/springboot/entity/CartItem.java
> +    private Book book;
add `@JoinColumn`s to avoid creating a third table for those relations

2024-05-20 09:38 UTC, karma-o commented on src/main/resources/db/changelog/changes/17-create-shopping_cart_cart_items.yaml
> +      id: create-shopping_cart_cart_items
this is redundant bacause we have a many-to-one relation and cart_item can just have a join column to store that relation

2024-05-20 10:18 UTC, DmytroHadiuchko commented on src/main/resources/db/changelog/changes/17-create-shopping_cart_cart_items.yaml
> +      id: create-shopping_cart_cart_items
I tried to delete it, but I got shema_validator problem, it wanted me to add this table

2024-05-21 10:01 UTC, yevheniisynytsia approved these changes

2024-05-21 10:01 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/controller/ShoppingCartController.java
> +            @RequestBody @Valid AddCartItemDto addCartItemDto,@AuthenticationPrincipal User user) {
```suggestion
            @RequestBody @Valid AddCartItemDto addCartItemDto, @AuthenticationPrincipal User user) {
```

2024-05-21 10:01 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/entity/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-05-21 10:01 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/entity/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
    @EqualsAndHashCode.Exclude
```

2024-05-21 14:25 UTC, merged