changed repository, added liquidbase, added softe delete
DmytroHadiuchko/Spring-BOOT pull request #3
Opened 2024-04-22 16:30 UTC by DmytroHadiuchko

2024-04-22 18:50 UTC, oksana-miazina approved these changes
Quality work!

2024-04-22 18:50 UTC, oksana-miazina commented on pom.xml
> +            <version>${liquibase.version}</version>
It seems you don't have property `liquibase.version`

2024-04-22 18:50 UTC, oksana-miazina commented on src/main/java/dmytro/hadiuchko/springboot/entity/Book.java
> +@Where(clause = "is_deleted=false")
Since `@Where` is deprecated now, it is possible to use `@SQLRestriction`

2024-04-22 18:50 UTC, oksana-miazina commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/BookServiceImpl.java
> +        book.setCoverImage(bookRequestDto.getCoverImage());
I'm not sure, maybe it's better to use mapper here

2024-04-23 09:51 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/service/impl/BookServiceImpl.java
> +        book.setCoverImage(bookRequestDto.getCoverImage());
it's ok here

2024-04-23 09:55 UTC, yevheniisynytsia requested changes
Well done! Left small comments

2024-04-23 09:55 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
primary key is not nullable by default, can be removed

2024-04-23 09:55 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  constraints:
please add `defaultValueBoolean: false`

2024-04-23 10:42 UTC, merged