addet pagination,Sorting, Swagger
DmytroHadiuchko/Spring-BOOT pull request #6
Opened 2024-04-29 12:39 UTC by DmytroHadiuchko

2024-05-01 13:40 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-01 13:40 UTC, andrii-hoienko commented on src/main/java/dmytro/hadiuchko/springboot/controller/BookController.java
> +            + "books according param")
```suggestion
    @Operation(summary = "search book according to search parameters", description = "filter and returns "
            + "books according to search parameters")

```

2024-05-01 13:40 UTC, andrii-hoienko commented on pom.xml
> +            <version>2.1.0</version>
Please use variable to define version like you did n other dependencies

2024-05-02 09:20 UTC, yevheniisynytsia approved these changes

2024-05-02 09:20 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/controller/BookController.java
> +    @Operation(summary = "get product by id", description = "return book by id")
```suggestion
    @Operation(summary = "Get product by id", description = "Return book by id")
```
let's make those pretty

2024-05-02 09:20 UTC, yevheniisynytsia commented on src/main/java/dmytro/hadiuchko/springboot/controller/BookController.java
> +    @Operation(summary = "create a new book", description = "create a new book")
same for others

2024-05-02 09:24 UTC, merged